/**
 * Arithmetic in GF(2^8) as used by QR codes: the field generated by the
 * primitive polynomial x^8 + x^4 + x^3 + x^2 + 1 (0x11d) with generator α = 2.
 */

/** EXP[i] = α^i for i in 0..254 (EXP[255] wraps back to 1). */
export const EXP: Uint8Array = new Uint8Array(256);
/** LOG[x] = i such that α^i = x, for x in 1..255. LOG[0] is undefined (0). */
export const LOG: Uint8Array = new Uint8Array(256);

for (let i = 0, x = 1; i < 255; i++) {
  EXP[i] = x;
  LOG[x] = i;
  x <<= 1;
  if (x & 0x100) x ^= 0x11d;
}
EXP[255] = EXP[0];

/** Multiply two field elements. */
export function gfMul(a: number, b: number): number {
  return a === 0 || b === 0 ? 0 : EXP[(LOG[a] + LOG[b]) % 255];
}
